'use strict';
/*
 * extract.js — slices the ACTUAL physics source out of Afterburn_Prototype.html
 * and writes prototype-slices.js, wrapped so it runs under three-shim.js.
 *
 * Sliced verbatim (byte-for-byte, located by the file's unique section-header
 * comments; nothing is retyped):
 *   1. TUNING section     — DEFAULTS (the 12 frozen values), SLIDER_DEFS,
 *                           and `const T = Object.assign({}, DEFAULTS);`
 *   2. DATA MODEL section — HULLS + PILOTS tables
 *   3. TrackSystem IIFE   — `const Track = (function(){ ... })();`
 *   4. Racer class        — EnergyCore + ShipController + PilotAbility
 *
 * After the slices, Racer.prototype.buildMesh is REPLACED with a physics-inert
 * stub (no THREE scene graph); every physics-relevant line stays untouched.
 */

const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, '..', '..', 'docs', 'Afterburn_Prototype.html');
const OUT = path.join(__dirname, 'prototype-slices.js');

// Slice [startMarker, endMarker) — endMarker excluded, so each slice runs up to
// the next section's header comment.
function slice(src, startMarker, endMarker, label) {
  const a = src.indexOf(startMarker);
  if (a < 0) throw new Error(`extract: start marker not found for "${label}": ${startMarker}`);
  if (src.indexOf(startMarker, a + 1) >= 0) throw new Error(`extract: start marker not unique for "${label}"`);
  const b = src.indexOf(endMarker, a);
  if (b < 0) throw new Error(`extract: end marker not found for "${label}": ${endMarker}`);
  return src.slice(a, b);
}

function mustContain(text, needles, label) {
  for (const n of needles) {
    if (!text.includes(n)) throw new Error(`extract: slice "${label}" is missing expected content: ${n}`);
  }
}

function extract() {
  const html = fs.readFileSync(SRC, 'utf8');

  const tuning = slice(html,
    '/* ---------------------- TUNING',
    '/* ------------------------------ DATA MODEL', 'tuning');
  mustContain(tuning, [
    'const DEFAULTS = {',
    "'energy.max':100",
    "'boost.drainPerSec':25",
    "'shield.speedCap':0.80",
    'const T = Object.assign({}, DEFAULTS);',
  ], 'tuning');

  const data = slice(html,
    '/* ------------------------------ DATA MODEL',
    '/* ------------------------------ THREE SETUP', 'data');
  mustContain(data, [
    'const HULLS = {',
    "medium: {key:'medium'",
    'maxEnergy:100',
    'const PILOTS = {',
    "vex:  {key:'vex'",
  ], 'data');

  const track = slice(html,
    '/* ============================ TrackSystem',
    '/* ============================ CombatSystem', 'track');
  mustContain(track, [
    'const Track = (function(){',
    "new THREE.CatmullRomCurve3(raw, true, 'catmullrom', 0.5)",
    'const LEN = curve.getLength();',
    'function nearest(pos)',
    'function innerAllow(idx, hullKey)',
    'return {curve, LEN, N, HALF, samples, nearest, innerAllow, breakHeavy, zones, group};',
  ], 'track');

  const racer = slice(html,
    '/* =============================== Racer',
    '/* ============================ RaceDirector', 'racer');
  mustContain(racer, [
    'class Racer {',
    'updatePlayer(dt, input)',
    'resolveWalls(np)',
    'forwardVec()',
    'tickCommon(dt)',
    'this.baseTop = 62 * this.hull.topSpeed;',
  ], 'racer');

  const out = [
    '// AUTO-GENERATED by extract.js — DO NOT EDIT.',
    '// Physics source sliced VERBATIM from docs/Afterburn_Prototype.html; only the',
    '// surrounding harness globals and the buildMesh stub below are hand-written.',
    "'use strict';",
    "const THREE = require('./three-shim.js');",
    '',
    '/* ---- Harness globals the sliced prototype code expects (see README) ---- */',
    'const scene = { add(){}, remove(){} };',
    'const HUD = { toast(){} };',
    'const stats = { shots:0, hits:0, bountyHits:0, boostTime:0 };',
    '// NOTE: the prototype reads Game.stats (Game.stats.shots++, Game.stats.boostTime+=dt),',
    '// so the stats object is attached to Game as well as exported standalone.',
    "const Game = { decoy:null, bountyLeader:null, spawnDecoy(){}, time:0, state:'racing', stats };",
    'const Combat = { fire(){} };',
    '',
    '/* ==================== BEGIN VERBATIM SLICES ==================== */',
    tuning.trimEnd(),
    '',
    data.trimEnd(),
    '',
    track.trimEnd(),
    '',
    racer.trimEnd(),
    '/* ===================== END VERBATIM SLICES ===================== */',
    '',
    '/* buildMesh replaced with a physics-inert stub: no THREE scene graph.',
    ' * - mesh.position must be a REAL Vector3 (place()/updatePlayer() integrate on it).',
    ' * - mesh.children: [] — tickCommon() runs this.mesh.children.forEach(...) EVERY frame.',
    ' * - mesh.traverse: no-op — tickCommon() intangible branch (never hit in the trace).',
    ' * - thruster.scale.setScalar must return an object with .multiplyScalar because',
    ' *   updatePlayer() chains .setScalar(...).multiplyScalar(...).',
    ' */',
    'Racer.prototype.buildMesh = function () {',
    '  this.mesh = {',
    '    position: new THREE.Vector3(),',
    '    rotation: { x: 0, y: 0, z: 0 },',
    '    children: [],',
    '    traverse() {},',
    '  };',
    '  this.thruster = {',
    '    scale: { setScalar() { return this; }, multiplyScalar() { return this; } },',
    '    material: { color: { setHex() {} } },',
    '  };',
    '};',
    '',
    'module.exports = { THREE, T, DEFAULTS, SLIDER_DEFS, HULLS, PILOTS, Track, Racer, Game, Combat, HUD, scene, stats };',
    '',
  ].join('\n');

  fs.writeFileSync(OUT, out);
  return OUT;
}

module.exports = { extract, SRC, OUT };

if (require.main === module) {
  console.log('wrote', extract());
}
