// AUTO-GENERATED by extract.js — DO NOT EDIT.
// Physics source sliced VERBATIM from docs/Afterburn_Prototype.html; only the
// surrounding harness globals and the buildMesh stub below are hand-written.
'use strict';
const THREE = require('./three-shim.js');

/* ---- Harness globals the sliced prototype code expects (see README) ---- */
const scene = { add(){}, remove(){} };
const HUD = { toast(){} };
const stats = { shots:0, hits:0, bountyHits:0, boostTime:0 };
// NOTE: the prototype reads Game.stats (Game.stats.shots++, Game.stats.boostTime+=dt),
// so the stats object is attached to Game as well as exported standalone.
const Game = { decoy:null, bountyLeader:null, spawnDecoy(){}, time:0, state:'racing', stats };
const Combat = { fire(){} };

/* ==================== BEGIN VERBATIM SLICES ==================== */
/* ---------------------- TUNING (all 12 live sliders) ---------------------- */
const DEFAULTS = {
  'energy.max':100, 'energy.regenPerSec':8,
  'boost.drainPerSec':25, 'boost.speedMult':1.40,
  'fire.cost':20, 'fire.speedDip':0.90,
  'shield.drainPerSec':15, 'shield.damageMult':0.40, 'shield.speedCap':0.80,
  'bounty.rewardMult':2.0, 'ability.cooldownScale':1.0, 'race.laps':3
};
const SLIDER_DEFS = [
  ['energy.max','Energy · max (× hull)',50,200,1],
  ['energy.regenPerSec','Energy · regen/s (× hull)',0,25,0.5],
  ['boost.drainPerSec','Boost · drain/s',5,60,1],
  ['boost.speedMult','Boost · top-speed ×',1.0,2.0,0.05],
  ['fire.cost','Fire · cost/shot',5,50,1],
  ['fire.speedDip','Fire · speed dip ×',0.5,1.0,0.01],
  ['shield.drainPerSec','Shield · drain/s',5,40,1],
  ['shield.damageMult','Shield · incoming dmg ×',0.0,1.0,0.05],
  ['shield.speedCap','Shield · speed cap ×',0.5,1.0,0.05],
  ['bounty.rewardMult','Bounty · reward ×',1.0,4.0,0.1],
  ['ability.cooldownScale','Ability · cooldown ×',0.5,2.0,0.05],
  ['race.laps','Race · laps',1,6,1],
];
const T = Object.assign({}, DEFAULTS);   // live tuning store (flat keys)

/* ------------------------------ DATA MODEL -------------------------------- */
// HullSpec — three sidegrades. maxEnergy/regen are absolute; sliders scale them.
const HULLS = {
  light:  {key:'light', name:'Light',  color:0x37d0ff, maxEnergy:80,  regen:11, topSpeed:1.15, mass:0.8, radius:1.6,
           tag:'Fits narrow gaps', desc:'Fast, fragile, thirsty pool. Squeezes through the Light Gap shortcut.'},
  medium: {key:'medium',name:'Medium', color:0x9d7bff, maxEnergy:100, regen:8,  topSpeed:1.00, mass:1.0, radius:2.0,
           tag:'Balanced',         desc:'No gate access, no weakness. The honest default.'},
  heavy:  {key:'heavy', name:'Heavy',  color:0xff8a3c, maxEnergy:130, regen:5,  topSpeed:0.88, mass:1.4, radius:2.6,
           tag:'Smashes walls',    desc:'Slow but a huge pool. Rams through the Heavy Wall shortcut.'},
};
// PilotAbility — one per match, cooldown-gated. Upgrades = cooldown only (not modelled in proto).
const PILOTS = {
  vex:  {key:'vex', name:'Vex',  ability:'EMP Pulse',  cd:18, desc:'Drains 30 energy from nearby rivals.'},
  sora: {key:'sora',name:'Sora', ability:'Phase Shift',cd:15, desc:'1.2s intangible — pass through walls & shots.'},
  kade: {key:'kade',name:'Kade', ability:'Siphon',     cd:20, desc:'Your next hit steals 25 energy.'},
  nyx:  {key:'nyx', name:'Nyx',  ability:'Decoy',       cd:22, desc:'Spawns a decoy that draws enemy fire 3s.'},
};

/* ============================ TrackSystem ================================= */
const Track = (function(){
  // Star-convex closed loop: radius varies around the circle so it can never cusp/double back.
  // Dips in `shape` make corners; peaks make straights. Min radius stays well above ship turn radius.
  const R0 = 300;
  const shape = [1.00,0.94,0.78,0.74,0.92,1.06,1.10,0.86,0.72,0.82,1.02,1.08,0.92,0.84];
  const raw = shape.map((m,i)=>{ const a = i/shape.length*Math.PI*2;
    return new THREE.Vector3(Math.cos(a)*R0*m, 0, Math.sin(a)*R0*m); });
  const curve = new THREE.CatmullRomCurve3(raw, true, 'catmullrom', 0.5);
  const LEN = curve.getLength();
  const N = 700;                       // dense samples for player collision + rendering
  const HALF = 17;                     // track half-width
  const samples = [];                  // {pos, tan, nrm}
  for(let i=0;i<N;i++){
    const t=i/N; const pos=curve.getPointAt(t); const tan=curve.getTangentAt(t).normalize();
    const nrm=new THREE.Vector3().crossVectors(tan, new THREE.Vector3(0,1,0)).normalize();
    samples.push({pos, tan, nrm});
  }
  // Shortcut zones (spec-gated). Inside = +normal side. Allow crossing wall if hull qualifies.
  // idxA/idxB chosen on bends where cutting the chord actually saves distance.
  const zones = [
    {type:'light', from:Math.floor(N*0.20), to:Math.floor(N*0.24), extra:20, side:1, broken:false},
    {type:'heavy', from:Math.floor(N*0.61), to:Math.floor(N*0.66), extra:22, side:1, broken:false},
  ];

  function buildRibbon(offInner, offOuter, mat, y){
    const g=new THREE.BufferGeometry(); const verts=[]; const M=N;
    for(let i=0;i<=M;i++){ const s=samples[i%M];
      const a=s.pos.clone().addScaledVector(s.nrm, offOuter); a.y=y;
      const b=s.pos.clone().addScaledVector(s.nrm, offInner); b.y=y;
      verts.push(a,b);
    }
    const arr=[]; for(let i=0;i<M;i++){ const a=verts[i*2],b=verts[i*2+1],c=verts[i*2+2],d=verts[i*2+3];
      arr.push(a.x,a.y,a.z, b.x,b.y,b.z, c.x,c.y,c.z);  arr.push(b.x,b.y,b.z, d.x,d.y,d.z, c.x,c.y,c.z); }
    g.setAttribute('position', new THREE.BufferAttribute(new Float32Array(arr),3));
    g.computeVertexNormals();
    return new THREE.Mesh(g, mat);
  }
  function buildWall(off, mat){
    const g=new THREE.BufferGeometry(); const verts=[]; const M=N; const H=3.2;
    for(let i=0;i<=M;i++){ const s=samples[i%M];
      const base=s.pos.clone().addScaledVector(s.nrm, off);
      const lo=base.clone(); lo.y=0; const hi=base.clone(); hi.y=H; verts.push(lo,hi);
    }
    const arr=[]; for(let i=0;i<M;i++){ const a=verts[i*2],b=verts[i*2+1],c=verts[i*2+2],d=verts[i*2+3];
      arr.push(a.x,a.y,a.z, b.x,b.y,b.z, c.x,c.y,c.z);  arr.push(b.x,b.y,b.z, d.x,d.y,d.z, c.x,c.y,c.z); }
    g.setAttribute('position', new THREE.BufferAttribute(new Float32Array(arr),3));
    g.computeVertexNormals();
    return new THREE.Mesh(g, mat);
  }

  const group = new THREE.Group();
  const roadMat = new THREE.MeshStandardMaterial({color:0x12203c, roughness:.9, metalness:.1});
  group.add(buildRibbon(-HALF, HALF, roadMat, 0.02));
  const laneMat = new THREE.MeshStandardMaterial({color:0x1c2f57, emissive:0x0a1830, roughness:.6});
  group.add(buildRibbon(-0.6, 0.6, laneMat, 0.05));          // centre line
  const wallMat = new THREE.MeshStandardMaterial({color:0x2b4d8f, emissive:0x0d2350, roughness:.5, side:THREE.DoubleSide});
  const wOut=buildWall(HALF+0.4, wallMat), wIn=buildWall(-HALF-0.4, wallMat);
  group.add(wOut, wIn);

  // ground grid for depth
  const grid=new THREE.GridHelper(1600,80,0x11305f,0x0a1c3a); grid.position.y=-0.4; group.add(grid);

  // start/finish gate
  function gateAt(idx, color){ const s=samples[idx%N];
    const t=new THREE.Mesh(new THREE.TorusGeometry(HALF+1,0.5,8,24),
      new THREE.MeshStandardMaterial({color, emissive:color, emissiveIntensity:.6}));
    t.position.copy(s.pos); t.position.y=HALF-2;
    t.lookAt(s.pos.clone().add(s.tan)); t.rotateX(Math.PI/2); group.add(t);
  }
  gateAt(0, 0xffffff);

  // shortcut markers (pillars for light gap, wall slab for heavy)
  const shortcutMeshes=[];
  zones.forEach(z=>{
    const mid=samples[Math.floor((z.from+z.to)/2)];
    if(z.type==='light'){
      const gapMat=new THREE.MeshStandardMaterial({color:0x37d0ff, emissive:0x0a3a55, emissiveIntensity:.7});
      [-1,1].forEach(sgn=>{ const p=new THREE.Mesh(new THREE.CylinderGeometry(1.1,1.1,7,10), gapMat);
        p.position.copy(mid.pos.clone().addScaledVector(mid.nrm, (HALF+2)*z.side).addScaledVector(mid.tan, sgn*3.4));
        p.position.y=3.5; group.add(p);});
    } else {
      const slab=new THREE.Mesh(new THREE.BoxGeometry(10,6,1.4),
        new THREE.MeshStandardMaterial({color:0xff8a3c, emissive:0x5a2400, emissiveIntensity:.6}));
      slab.position.copy(mid.pos.clone().addScaledVector(mid.nrm,(HALF+3)*z.side)); slab.position.y=3;
      slab.lookAt(mid.pos); z.slab=slab; group.add(slab);
      shortcutMeshes.push(slab);
    }
  });
  scene.add(group);

  // nearest sample (full search — only run for the player; cheap at N=700)
  function nearest(pos){ let bi=0,bd=1e9;
    for(let i=0;i<N;i++){ const dx=pos.x-samples[i].pos.x, dz=pos.z-samples[i].pos.z; const d=dx*dx+dz*dz;
      if(d<bd){bd=d;bi=i;} } return bi; }

  // effective inner allowance at index for a hull (shortcut gating)
  function innerAllow(idx, hullKey){ let a=0;
    for(const z of zones){ const inRange = z.from<=z.to ? (idx>=z.from&&idx<=z.to) : (idx>=z.from||idx<=z.to);
      if(!inRange) continue;
      if(z.type==='light' && hullKey==='light') a=Math.max(a,z.extra);
      if(z.type==='heavy' && (hullKey==='heavy'||z.broken)) a=Math.max(a,z.extra);
    } return a; }
  function breakHeavy(idx){ for(const z of zones){ if(z.type==='heavy'){ const inRange=idx>=z.from&&idx<=z.to;
    if(inRange && !z.broken){ z.broken=true; if(z.slab){ z.slab.visible=false; } return true; } } } return false; }

  return {curve, LEN, N, HALF, samples, nearest, innerAllow, breakHeavy, zones, group};
})();

/* =============================== Racer =================================== */
// Owns EnergyCore + ShipController + PilotAbility for one craft (player or ghost).
class Racer {
  constructor(hullKey, pilotKey, isPlayer, colorOverride){
    this.hull=HULLS[hullKey]; this.pilot=PILOTS[pilotKey]; this.isPlayer=isPlayer;
    this.maxEnergy = this.hull.maxEnergy * (T['energy.max']/100);
    this.energy = this.maxEnergy;
    this.heading=0; this.speed=0; this.progress=0; this.prevFrac=0;
    this.spinout=0; this.cd=0; this.intangible=0; this.siphonArmed=false;
    this.shielding=false; this.boosting=false; this.firing=false;
    this.finished=false; this.finishTime=0;
    this.baseTop = 62 * this.hull.topSpeed;                // units/s baseline top speed
    // AI feel
    this.ai = !isPlayer ? {t:Math.random()*0.02, skill:0.80+Math.random()*0.10, aggro:Math.random()} : null;
    this.buildMesh(colorOverride!=null?colorOverride:this.hull.color);
  }
  buildMesh(color){
    const g=new THREE.Group();
    const body=new THREE.Mesh(new THREE.ConeGeometry(1.5,5,4),
      new THREE.MeshStandardMaterial({color, emissive:color, emissiveIntensity:.25, metalness:.4, roughness:.4}));
    body.rotation.x=Math.PI/2; body.rotation.z=Math.PI/4; g.add(body);
    const wing=new THREE.Mesh(new THREE.BoxGeometry(5,0.4,1.6),
      new THREE.MeshStandardMaterial({color:0x223, metalness:.5})); wing.position.z=-1.2; g.add(wing);
    const glow=new THREE.Mesh(new THREE.SphereGeometry(0.9,8,8),
      new THREE.MeshBasicMaterial({color:0xff7a3c})); glow.position.z=-2.6; this.thruster=glow; g.add(glow);
    this.mesh=g; scene.add(g);
  }
  forwardVec(){ return new THREE.Vector3(Math.sin(this.heading),0,Math.cos(this.heading)); }

  // -------- EnergyCore: single gate for all spending --------
  canSpend(cost){ return this.energy>=cost; }

  place(){ // place at start line
    const s=Track.samples[0]; const lane=(this._lane||0);
    this.mesh.position.copy(s.pos).addScaledVector(s.nrm, lane*5);
    this.heading=Math.atan2(s.tan.x, s.tan.z);
    this.mesh.position.y=1.2;
  }

  updatePlayer(dt, input){
    const top=this.baseTop;
    // resolve mutually-exclusive active mode (EnergyCore is the arbiter)
    this.boosting=false; this.shielding=false; this.firing=false;
    let spend='COAST';
    // priority: last pressed among boost/shield wins; fire is discrete & blocked by the others
    if(input.boost && this.canSpend(1)){ this.boosting=true; spend='BOOST'; }
    else if(input.shield && this.canSpend(1)){ this.shielding=true; spend='SHIELD'; }

    // fire (tap) only when neither boost nor shield active
    if(input.fire && !this.boosting && !this.shielding && this.fireTimer<=0 && this.canSpend(T['fire.cost'])){
      this.energy-=T['fire.cost']; this.fireTimer=0.28; this.firing=true; spend='FIRE';
      this.speed*=T['fire.speedDip'];
      Combat.fire(this, this.siphonArmed); Game.stats.shots++;
    }
    this.fireTimer=Math.max(0,(this.fireTimer||0)-dt);

    // energy drain / regen
    if(this.boosting){ this.energy-=T['boost.drainPerSec']*dt; if(this.energy<=0){this.energy=0;this.boosting=false;} }
    else if(this.shielding){ this.energy-=T['shield.drainPerSec']*dt; if(this.energy<=0){this.energy=0;this.shielding=false;} }
    else if(!this.firing){ // regen only in true downtime
      this.energy+=this.hull.regen*(T['energy.regenPerSec']/8)*dt;
    }
    this.energy=Math.min(this.maxEnergy, Math.max(0,this.energy));
    if(this.boosting) Game.stats.boostTime+=dt;

    // speed target
    let cap=top;
    if(this.boosting) cap=top*T['boost.speedMult'];
    else if(this.shielding) cap=top*T['shield.speedCap'];
    if(this.spinout>0) cap*=0.55;
    const accel = input.thrust? 55 : 0;
    if(input.thrust) this.speed += accel*dt;
    if(input.brake)  this.speed -= 80*dt;
    this.speed -= this.speed*0.6*dt;                        // drag
    this.speed=Math.max(0, Math.min(cap, this.speed));

    // steering (less bite at crawl)
    const steer=(input.left?1:0)-(input.right?1:0);
    const bite=Math.min(1, this.speed/25+0.2);
    this.heading += steer*2.4*dt*bite;

    // integrate + wall collision
    const fwd=this.forwardVec();
    const np=this.mesh.position.clone().addScaledVector(fwd, this.speed*dt);
    this.resolveWalls(np);
    this.mesh.position.x=np.x; this.mesh.position.z=np.z; this.mesh.position.y=1.2;
    this.mesh.rotation.y=this.heading;

    this.tickCommon(dt);
    this.thruster.scale.setScalar(this.boosting?1.8:1).multiplyScalar(0.6+this.speed/top*0.6);
    this.thruster.material.color.setHex(this.boosting?0xffe14d:0xff7a3c);
  }

  resolveWalls(np){
    if(this.intangible>0) return;                           // Sora phase = ignore walls
    const i=Track.nearest(np); const s=Track.samples[i];
    const v=np.clone().sub(s.pos); const off=v.dot(s.nrm);
    const allow=Track.innerAllow(i, this.hull.key);
    const limInner = Track.HALF + (allow) - this.hull.radius;   // +allow only on inside(+normal)
    const limOuter = -(Track.HALF - this.hull.radius);
    // heavy smashes the slab on contact
    if(off > Track.HALF - this.hull.radius && this.hull.key==='heavy'){
      if(Track.breakHeavy(i)){ HUD.toast('WALL SMASHED', '#ff8a3c'); }
    }
    let clampedOff=off;
    if(off>limInner) clampedOff=limInner;
    if(off<limOuter) clampedOff=limOuter;
    if(clampedOff!==off){ this.speed*=0.92;                 // gentle scrape, not a dead stop
      // slide along the wall: nudge heading toward the track tangent so you don't pin nose-in
      const tanH=Math.atan2(s.tan.x, s.tan.z);
      let dh=((tanH-this.heading+Math.PI*3)%(Math.PI*2))-Math.PI; this.heading+=dh*0.18;
      const corrected=s.pos.clone().addScaledVector(s.nrm, clampedOff); np.x=corrected.x; np.z=corrected.z; }
  }

  updateGhost(dt, racers){
    // GhostSystem: follows the centreline with a simulated energy loop → PvP feel, zero netcode.
    const a=this.ai; const curLen=Track.LEN;
    // energy discipline: boost on straights when full-ish, coast when low
    const idx=Math.floor(a.t*Track.N)%Track.N;
    const curv = 1 - Math.abs(Track.samples[idx].tan.dot(Track.samples[(idx+8)%Track.N].tan));
    const straight = curv < 0.02;
    let cap=this.baseTop;
    if(this.spinout>0){ cap*=0.55; }
    else if(this.energy > this.maxEnergy*0.35 && straight){ this.boosting=true;
      cap=this.baseTop*T['boost.speedMult']*a.skill; this.energy-=T['boost.drainPerSec']*dt; }
    else { this.boosting=false; this.energy+=this.hull.regen*(T['energy.regenPerSec']/8)*dt; }
    this.energy=Math.min(this.maxEnergy,Math.max(0,this.energy));
    cap*=a.skill;
    this.speed += (cap-this.speed)*Math.min(1,dt*3);
    a.t += (this.speed*dt)/curLen;
    if(a.t>=1){ a.t-=1; }
    // AI aggression: fire at bounty leader if close behind
    a.fireCd=(a.fireCd||0)-dt;
    if(a.aggro>0.4 && Game.bountyLeader && Game.bountyLeader!==this && a.fireCd<=0){
      const tgt=Game.decoy||Game.bountyLeader;
      if(this.mesh.position.distanceTo(tgt.mesh.position)<55 && this.energy>T['fire.cost']){
        this.energy-=T['fire.cost']; a.fireCd=1.4+Math.random(); Combat.fire(this,false);
      }
    }
    const s=Track.curve.getPointAt(a.t); const tan=Track.curve.getTangentAt(a.t);
    const lane=this._lane||0; const nrm=new THREE.Vector3().crossVectors(tan,new THREE.Vector3(0,1,0)).normalize();
    this.mesh.position.copy(s).addScaledVector(nrm, lane*4); this.mesh.position.y=1.2;
    this.heading=Math.atan2(tan.x,tan.z); this.mesh.rotation.y=this.heading;
    this.progress = this.laps + a.t;
    this.tickCommon(dt);
    this.thruster.scale.setScalar(this.boosting?1.6:0.9);
    // lap wrap for ghosts
    if(a.t < this.prevFrac-0.5){ this.laps=(this.laps||0)+1; }
    this.prevFrac=a.t;
    if(this.progress>=T['race.laps'] && !this.finished){ this.finished=true; this.finishTime=Game.time; }
  }

  tickCommon(dt){
    if(this.spinout>0) this.spinout-=dt;
    if(this.intangible>0){ this.intangible-=dt; this.mesh.traverse(o=>{ if(o.material) o.material.transparent=true; });
      this.mesh.children.forEach(c=>{ if(c.material) c.material.opacity=0.4; }); }
    else this.mesh.children.forEach(c=>{ if(c.material){ c.material.opacity=1; } });
    if(this.cd>0) this.cd-=dt;
  }

  // progress bookkeeping for the PLAYER (unwrapped)
  updatePlayerProgress(){
    const i=Track.nearest(this.mesh.position); let frac=i/Track.N;
    let d=frac-this.prevFrac;
    if(d<-0.5) this.laps=(this.laps||0)+1;
    else if(d>0.5) this.laps=(this.laps||0)-1;
    this.prevFrac=frac; this.progress=(this.laps||0)+frac;
    if(this.progress>=T['race.laps'] && !this.finished){ this.finished=true; this.finishTime=Game.time; }
  }

  activateAbility(){
    if(this.cd>0) return;
    const cd=this.pilot.cd*T['ability.cooldownScale'];
    switch(this.pilot.key){
      case 'vex': Game.racers.forEach(r=>{ if(r!==this && r.mesh.position.distanceTo(this.mesh.position)<70){
          r.energy=Math.max(0,r.energy-30); } }); HUD.toast('EMP PULSE','#37d0ff'); break;
      case 'sora': this.intangible=1.2; HUD.toast('PHASE SHIFT','#9d7bff'); break;
      case 'kade': this.siphonArmed=true; HUD.toast('SIPHON ARMED','#38f5c9'); break;
      case 'nyx': Game.spawnDecoy(this); HUD.toast('DECOY OUT','#ffd23f'); break;
    }
    this.cd=cd; this.cdMax=cd;
  }
}
/* ===================== END VERBATIM SLICES ===================== */

/* buildMesh replaced with a physics-inert stub: no THREE scene graph.
 * - mesh.position must be a REAL Vector3 (place()/updatePlayer() integrate on it).
 * - mesh.children: [] — tickCommon() runs this.mesh.children.forEach(...) EVERY frame.
 * - mesh.traverse: no-op — tickCommon() intangible branch (never hit in the trace).
 * - thruster.scale.setScalar must return an object with .multiplyScalar because
 *   updatePlayer() chains .setScalar(...).multiplyScalar(...).
 */
Racer.prototype.buildMesh = function () {
  this.mesh = {
    position: new THREE.Vector3(),
    rotation: { x: 0, y: 0, z: 0 },
    children: [],
    traverse() {},
  };
  this.thruster = {
    scale: { setScalar() { return this; }, multiplyScalar() { return this; } },
    material: { color: { setHex() {} } },
  };
};

module.exports = { THREE, T, DEFAULTS, SLIDER_DEFS, HULLS, PILOTS, Track, Racer, Game, Combat, HUD, scene, stats };
